wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1678041773.974782
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.7.9
      5: 0.13.10
      8:
      - 3
      - 5
architecture:
  desc: null
  value: Model2
dataset:
  desc: null
  value: cornell
dropout-prob:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 2
